---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-export
  namespace: nfs-ganesha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-ganesha

