NFS_CORE_PARAM {
    Protocols = 4;         # solo NFSv4.x
    Enable_UDP = false;    # non creare listener/registrazioni UDP
    Enable_NLM = false;    # NLM è per NFSv3, non serve con v4
    Enable_RQUOTA = false; # rquota è per v3, disabilitalo
}
# Se non usi Kerberos:
NFS_KRB5 { Active_krb5 = false; }

# Inutile
#DBUS { Enable = false;}


EXPORT {
  Export_Id = 1;
  Path = /export;
  Pseudo = /export;
  Access_Type = RW;
  Squash = No_Root_Squash;
  SecType = sys;
  FSAL { Name = VFS; }
}
