NFS_Core_Param {
  NFS_Port = 2049;
  Protocols = 4;           # Solo NFSv4
  Bind_Addr = 0.0.0.0;
}

EXPORT {
  Export_Id = 1;
  Path = /export;
  Pseudo = /export;        # requisito NFSv4
  Access_Type = RW;
  Squash = No_Root_Squash; # valuta se usare root_squash in prod
  SecType = sys;
  FSAL {
    Name = VFS;
  }
}

